# Declaring all common properties across all microservices
info:
  app:
    developer:
      name: Amsidh Lokhande
      emailId: amsidhmicroservice@gmail.com

management:
  endpoint:
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  trace:
    http:
      enabled: true

spring:
  main:
    banner-mode: 'off'

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    rabbitmq:
      queue: zipkin
    sender:
      type: RABBIT

  rabbitmq:
    addresses: ${RABBIT_MQ_HOST:localhost}:${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

# Configure Eureka Client URL
eureka:
  client:
    service-url:
      - defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:8761/eureka
  